name: Deployment

#concurrency:
#  group: dev
#  cancel-in-progress: true

on: [push]
#on:
#  push:
#    branches:
#      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
#    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create dokcer image
        run: |
          cd ${{ github.workspace }}
          ls
          env