name: Deployment

#concurrency:
#  group: dev
#  cancel-in-progress: true

on: [push]
#on:
#  push:
#    branches:
#      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
#    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Create dokcer image
        run: echo ${{ github.repository }}
#        run: docker build -t zuzel:1.0 -f docker/Dockerfile .
      - name: Log in to ECR
        env:
          API_KEY: ${{ secrets.API_KEY }}