name: Deployment

env:
  ECR_URL: ${{ secrets.ZUZEL_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
  PROJECT_NAME: ${{ github.event.repository.name }}
  VERSION: 1.0.0

concurrency:
  group: dev
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  dokcer-build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ env.ECR_URL }}/${{ env.PROJECT_NAME }}:latest
            ${{ env.ECR_URL }}/${{ env.PROJECT_NAME }}:${{ env.VERSION }}
