name: Deployment

env:
  ECR_URL: 231514391836.dkr.ecr.eu-central-1.amazonaws.com
  PROJECT_NAME: ${{ github.event.repository.name }}
  VERSION: 1.0.0

concurrency:
  group: dev
  cancel-in-progress: true

on: [push]
#on:
#  push:
#    branches:
#      - main

jobs:
  dokcer-build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Create dokcer image
        run: |
          docker build -t $PROJECT_NAME:$VERSION -f docker/Dockerfile .
          docker images
      - name: Log in to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_URL
      - name: Push image
        run: |
          docker tag $PROJECT_NAME:$VERSION $ECR_URL/$PROJECT_NAME:$VERSION
          docker push $ECR_URL/$PROJECT_NAME:$VERSION
