name: Deployment

env:
  ECR_URL: 231514391836.dkr.ecr.eu-central-1.amazonaws.com
  PROJECT_NAME: ${{ github.event.repository.name }}
  VERSION: 1.0.0

concurrency:
  group: dev
  cancel-in-progress: true

on: [push]
#on:
#  push:
#    branches:
#      - main

jobs:
  dokcer-build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Create dokcer image
        run: |
          docker build -t $PROJECT_NAME:$VERSION -f docker/Dockerfile .
          docker images
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          push: true
          tags: |
            $ECR_URL/$PROJECT_NAME:latest
            $ECR_URL/$PROJECT_NAME:$VERSION
